ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-607' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /opt/anaconda3/envs/hi/lib/python3.10/site-packages/tornado/websocket.py:1086> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/hi/lib/python3.10/site-packages/tornado/websocket.py", line 1088, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/hi/lib/python3.10/site-packages/tornado/websocket.py", line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
ERROR:root:Module modules.export에서 오류 발생: Traceback (most recent call last):
  File "/Users/ENZO/KOOKIZ/GITHUB/mini-project-2/Home.py", line 55, in <module>
    getattr(module, ui_func_name)()
  File "/Users/ENZO/KOOKIZ/GITHUB/mini-project-2/modules/export.py", line 132, in export_ui
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
ValueError: too many values to unpack (expected 5)

ERROR:root:Module modules.export에서 오류 발생: Traceback (most recent call last):
  File "/Users/ENZO/KOOKIZ/GITHUB/mini-project-2/Home.py", line 55, in <module>
    getattr(module, ui_func_name)()
  File "/Users/ENZO/KOOKIZ/GITHUB/mini-project-2/modules/export.py", line 532, in export_ui
    with tab6:
NameError: name 'tab6' is not defined. Did you mean: 'tab1'?

ERROR:root:Module modules.dashboard에서 오류 발생: Traceback (most recent call last):
  File "/Users/ENZO/KOOKIZ/GITHUB/mini-project-2/Home.py", line 54, in <module>
    module = __import__(mod_path, fromlist=[ui_func_name])
  File "/Users/ENZO/KOOKIZ/GITHUB/mini-project-2/modules/dashboard.py", line 19, in <module>
    from modules.dashboard_exim import exchange_ui
ModuleNotFoundError: No module named 'modules.dashboard_exim'

ERROR:root:Module modules.export에서 오류 발생: Traceback (most recent call last):
  File "/Users/yeonu/yeonu/git/mini-project-2/Home.py", line 54, in <module>
    module = __import__(mod_path, fromlist=[ui_func_name])
  File "/Users/yeonu/yeonu/git/mini-project-2/modules/export.py", line 9, in <module>
    import ace_tools_open as tools
ModuleNotFoundError: No module named 'ace_tools_open'

ERROR:root:Module modules.prediction에서 오류 발생: Traceback (most recent call last):
  File "/Users/yeonu/yeonu/git/mini-project-2/Home.py", line 54, in <module>
    module = __import__(mod_path, fromlist=[ui_func_name])
  File "/Users/yeonu/yeonu/git/mini-project-2/modules/prediction.py", line 5, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

ERROR:root:Module modules.recommendations에서 오류 발생: Traceback (most recent call last):
  File "/Users/yeonu/yeonu/git/mini-project-2/Home.py", line 54, in <module>
    module = __import__(mod_path, fromlist=[ui_func_name])
  File "/Users/yeonu/yeonu/git/mini-project-2/modules/recommendations.py", line 4, in <module>
    from huggingface_hub import InferenceClient
ModuleNotFoundError: No module named 'huggingface_hub'

